/** Shared gameplay, collision, and camera tuning for Catchy. */
export const GAME_CONFIG = {
  simulation: {
    tickHz: 60,
    maxCatchUpSteps: 6,
  },
  player: {
    radius: 0.55,
    speed: 9.2,
    facingRotationSpeed: 10,
    jump: {
      height: 1.15,
      durationSeconds: 0.72,
    },
    dash: {
      durationSeconds: 0.18,
      distance: 4.2,
      cooldownSeconds: 2.5,
      cameraImpulseSeconds: 0.34,
      cameraFovIncrease: 5,
      trailSeconds: 0.22,
      hapticMs: 18,
    },
    speedBoost: {
      durationSeconds: 5,
      cooldownSeconds: 30,
      multiplier: 1.5,
      hapticMs: 16,
    },
    joystick: {
      radialDeadZone: 0.1,
      responseExponent: 1.08,
    },
  },
  npc: {
    radius: 0.48,
    speed: 8.2,
    respawnDelay: 0.7,
    minSpawnDistanceFromPlayer: 8,
    spawnSeparation: 1.8,
    navigation: {
      gridSpacing: 1.9,
      replanIntervalMin: 0.78,
      replanIntervalMax: 1.1,
      replanPhaseSpreadSeconds: 0.28,
      candidateDirections: 16,
      minFleeDistance: 12,
      preferredFleeDistance: 18,
      maxFleeDistance: 23,
      preferredRunnerRadius: 24,
      preferredRunnerSeparation: 5.2,
      preferredGoalSeparation: 8,
      boundarySteeringStartRadius: 23.5,
      boundarySteeringFullRadius: 27.5,
      boundaryInwardSteeringWeight: 0.8,
      boundaryOutwardDamping: 0.85,
      goalWeights: {
        distanceBand: 1.2,
        maxFleeDistancePenalty: 1.6,
        urgentFleeDistance: 3,
        moderateFleeDistance: 0.45,
        routeQuality: 0.42,
        routeDetour: 0.55,
        openSpace: 1.2,
        awayDirection: 2.8,
        lateralEscape: 1.9,
        personalLateralBias: 0.42,
        runnerSeparation: 2.2,
        goalSeparation: 5.5,
        crowdingPenalty: 1.4,
        boundaryPenalty: 0.62,
        previousRoutePenalty: 4.2,
      },
      stuckRecheck: 0.32,
      stuckMovementThreshold: 0.025,
      stuckSpeedThreshold: 1.2,
    },
  },
  captureDistance: 2,
  nearbyDistance: 9,
  targetSwitchRatio: 0.78,
  slowZone: {
    movementMultiplier: 0.55,
    recoverySeconds: 0.38,
  },
  elasticBounce: {
    releaseDistance: 0.14,
    playerSpeedMultiplier: 2.2,
  },
  barrier: {
    openSeconds: 5,
    closedSeconds: 5,
  },
  camera: {
    distance: 19,
    pitch: 20,
    lookAhead: 10.0,
    compositionOffset: 0.13,
    followYawSpeed: 4.5,
    turnAnticipation: 9,
    followResumeSpeed: 3.2,
    tuningRanges: {
      distance: { min: 0, max: 32, step: 0.5 },
      pitch: { min: 0, max: 65, step: 1 },
      lookAhead: { min: 0, max: 10, step: 0.1 },
      compositionOffset: { min: -0.15, max: 0.4, step: 0.01 },
      followYawSpeed: { min: 1, max: 10, step: 0.25 },
      turnAnticipation: { min: 0, max: 14, step: 1 },
      followResumeSpeed: { min: 0.5, max: 8, step: 0.25 },
    },
    manualYawSpeed: 2.25,
    manualPitchSpeed: 70,
    manualPersistenceSeconds: 0.65,
    followMovementSpeedThreshold: 0.4,
  },
  // These are animation dimensions, not map placement or collider data.
  interactiveObjects: {
    speedPad: { pulseSeconds: 0.42 },
    temporaryBarrier: { height: 1.55 },
  },
  capturePresentation: {
    captureSeconds: 0.43,
    afterSeconds: 0.31,
  },
  roundSeconds: 5 * 60,
  obstacleMargin: 0.12,
} as const;

/** Shared arena rim height; map radius comes from the active MapDefinition. */
export const ARENA = {
  rimHeight: 1.15,
};
